### ISSUE TITLE
Use existing Latitude and Longitude device attributes

### ISSUE THREAD

**Issue by adamjol** [jayyx2/wug-geolocation#2]
The device attributes already exist for Latitude and Longitude. Can you use these rather than recreate a new LatLong attribute for each device?

**Comment by jayyx2** [comment]
The code has been updated for this. In wug-geolocation.asp you will find the following. Simply switch to true/false depending on your preference.

///Use built-in Latitude and Longitude values?
var bUseBuiltin = false;
